Marshall/mock urlopen
arvkevi/img2cmap pull request #15
Opened 2022-05-23 14:58 UTC by mpkrass7

Essentially I just added a couple of web urls to the unit tests and validated that they work. If they aren't valid urls, they won't be tested. Please don't make me make a unit test to assess if the check for url validity is itself valid. 

Notes:
- In one of the unit tests, I don't check the web urls because the unit test checks the name attribute of the resulting colormap. I wasn't sure what the name should be so I left them out of that test
- Hi Kevin

2022-05-23 14:59 UTC, mpkrass7 commented
Hmm I'm seeing that some checks are not successful here

2022-05-23 21:28 UTC, mpkrass7 commented
Yay I think we're passing all of the tests. Adding exception handling for `OSError` was the key

2022-05-25 15:52 UTC, arvkevi requested changes

2022-05-25 18:06 UTC, mpkrass7 commented on pyproject.toml
> +    "requests"
Ahh thought I had removed it from there..

2022-05-26 00:10 UTC, arvkevi approved these changes
LGTM! Thank you @mpkrass7, this was a great find!

2022-05-26 18:00 UTC, merged